version: "3.8"

services:
  kong:
    image: kong:2.2-alpine
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_PLUGINS: bundled,poc
      KONG_LUA_PACKAGE_PATH: /home/?.lua;;
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes: 
      - ./kong.yml:/home/kong/kong.yml
      - ./plugins:/home/kong/plugins
